### ISSUE TITLE
Add ability to generate thumbnail in different formats

### ISSUE THREAD

**Issue by jkevingutierrez** [neon-jungle/wagtailvideos#100]
It would be great to have the ability to generate the thumbnail in different formats. In our case, we are aiming for webp because of https://developer.chrome.com/en/docs/lighthouse/performance/uses-webp-images/, but it would be great to have this as a configuration that could be modified.

**Comment by seb-b** [comment]
good suggestion, not sure if ffmpeg has that option but could use pillow to do the conversion. You can also manually upload webp versions of your thumbnails in the meantime too
