### ISSUE TITLE
The size of the uploaded video

### ISSUE THREAD

**Issue by eeyy** [neon-jungle/wagtailvideos#103]
Hello, can I change the parameter to the size of the video? By default there is 1 GB

**Comment by seb-b** [comment]
Yep, adjusting the `WAGTAILVIDEOS_MAX_UPLOAD_SIZE` setting can fix this. Ideally this should be documented somewhere. The default is 1GB.

```
WAGTAILVIDEOS_MAX_UPLOAD_SIZE = (1024 * 1024 * 1024) * 2 # 2GB
```

https://github.com/neon-jungle/wagtailvideos/blob/28371ee754851f1780029e8f536c528915344aef/wagtailvideos/fields.py#L13

**Comment by eeyy** [comment]
Thank you for the answer, you helped a lot. 
And do not tell me how to make the language change, I changed it on the whole site using LANGUAGE_CODE in the settings, but the txt from your library has not changed

**Comment by seb-b** [comment]
we don't have translations for this app unfortunately. If you'd like to open a pull request to add a translation you're more than welcome. Here's a similar PR where someone added french translation to a different app of ours: https://github.com/neon-jungle/wagtail-birdsong/pull/30/

**Comment by eeyy** [comment]
OK, I'll do it

**Comment by eeyy** [comment]
Is there something wrong with my edits, should I fix something?

**Comment by seb-b** [comment]
No everything looks good, I'll hopefully get a chance to merge and do a release by the end of the week, apologies for the delay!

**Comment by eeyy** [comment]
Thanks!
