### ISSUE TITLE
No locale files

### ISSUE THREAD

**Issue by eeyy** [neon-jungle/wagtailvideos#105]
Hello, I updated the version to 4.2.1, expecting to see localization there, but the locale folder is not loaded into the project, am I doing something wrong?
![1](https://github.com/neon-jungle/wagtailvideos/assets/43825054/5808012a-5292-4850-9439-2fe5907e1bcb)

**Comment by eeyy** [comment]
Migration files - 14

**Comment by seb-b** [comment]
I forgot to update the MANIFEST.in file to includes the locale folders, can you try again on the latest release (4.2.2) ?

**Comment by eeyy** [comment]
yes, thanks)
