### ISSUE TITLE
Customizing the get_upload_to() method via extending AbstractVideo

### ISSUE THREAD

**Issue by RyanKJ** [neon-jungle/wagtailvideos#27]
With wagtail images there is a way to customize the wagtail image model itself to override methods like get_upload_to() that are supplied to the FileField for example. You do this by defining your class and setting WAGTAILIMAGES_IMAGE_MODEL in the settings.py file.

Wagtailvideo does not appear to support this functionality like wagtail images? The Video model is hardcoded into the wagtailvideo views whereas the wagtail image model is not for vanilla wagtail. My end goal is to edit the value of get_upload_to(), unsure if there is another means to do this or the feature is purposefully omitted.

**Comment by seb-b** [comment]
That feature was left out because nobody has needed it until now!
I agree that it would be useful to use a custom model for the video in the same way as images, feel free to submit a pull request :slightly_smiling_face:
