### ISSUE TITLE
Support for Django 4.0

### ISSUE THREAD

**Issue by rossettistone** [neon-jungle/wagtailvideos#89]
Django 4.x has removed support or changed the interface for a number of methods that wagtailvideos depends upon. Would be helpful to have wagtailvideos handle those changes. I might be able to help with a PR at some point in the future (lacking bandwidth right now), but I see that there's already one going! https://github.com/neon-jungle/wagtailvideos/pull/87

Logging issue for tracking and in case there's any useful discussion to be had. :-)

**Comment by seb-b** [comment]
#87 merged in and deployed in version `2.11.0`
