### ISSUE TITLE
Is wagtailvidewos work in wagtail api

### ISSUE THREAD

**Issue by Alexey-Krapivnitsky** [neon-jungle/wagtailvideos#96]
Can I use the wagtailvideos in wagtail api? For exapmple for images I can use the next code:

from wagtail.api import APIField
from wagtail.images.api.fields import ImageRenditionField

api_fields = [        
        APIField('feed_image'),
        APIField('feed_image_thumbnail', serializer=ImageRenditionField('fill-100x100', source='feed_image')),
        ...
    ]
    
Is it possible for video?

**Comment by seb-b** [comment]
I don't reckon it'd work out of the box like that, but if you added router urls and your own serializers there's no reason that wouldn't work. They're all just models at the end of the day
